name: Cypress Tests

on: 
  push:
    branches:
      - 'master'
  # schedule:
  #   - cron: '0 11 * * *' # This runs the workflow every day at 11:00 AM UTC (7:00 AM MONTREAL time)

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        env: [dev, qa, staging]
    steps:
      - uses: actions/checkout@v4
      #- name: Run Cypress Tests
        #uses: cypress-io/github-action@v6
        # with:
        #   record: true
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run : npm install
      - run : npx cypress run --env ENV=${{ matrix.env }}
      
      # Uploader les rapports de test Mochawesome HTML
      - name: Upload Mochawesome HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-reports
          path: |
            cypress/reports/**/*
          retention-days: 14

      # Uploader les captures d'écran/vidéos en cas d'échec
      - name: Upload Screenshots 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*
          retention-days: 14

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*
          retention-days: 14
      

