name: Cypress Tests

on: 
  push:
    branches:
      - 'master'
  # schedule:
  #   - cron: '0 11 * * *' # This runs the workflow every day at 11:00 AM UTC (7:00 AM MONTREAL time)

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        env: [dev, qa, staging]
    steps:
      - uses: actions/checkout@v4
      #- name: Run Cypress Tests
        #uses: cypress-io/github-action@v6
        # with:
        #   record: true
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run : npm install
      - run : npx cypress run --env ENV=${{ matrix.env }}

